name: Build & Test (Android)
on:
  push: 
    branches: [master]
#    paths:
#      - 'noty-android/**'
  pull_request:
    branches: [master]
    paths:
      - 'noty-android/**'

jobs:
  build:
    name: Build & Test Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.5.3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Grant Permission to Execute
        run: chmod +x gradlew
        working-directory: noty-android

      - name: ðŸ— Build with Gradle ðŸ› ï¸
        run: ./gradlew ktlintCheck test assembleDebug --stacktrace
        working-directory: noty-android
        
      - name: Enable KVM for hardware acceleration
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
        
      - name: ðŸ§ª Run UI Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86
          disable-animations: true
          script: cd noty-android && ./gradlew :app:composeapp:connectedCheck --stacktrace

      - name: ðŸ“Š Generate compose compiler report ï¸
        if: github.event_name == 'push'
        run: ./gradlew releaseComposeCompilerHtmlReport --stacktrace
        working-directory: noty-android

      - name: â¬†ï¸ Update compose compiler report ï¸in the project
        if: github.event_name == 'push'
        run: |
          mv -f noty-android/app/composeapp/build/compose_report/index.html docs/pages/noty-android/compose_report.html
          git config user.name $GITHUB_ACTOR
          git config user.email action@github.com
          echo "Compose Report Generated by $GITHUB_RUN_NUMBER via $GITHUB_EVENT_NAME on $(date +"%Y-%m-%d %r")" > docs/pages/noty-android/compose_report.meta
          git add docs/pages/noty-android/compose_report.html
          git add docs/pages/noty-android/compose_report.meta
          git commit -m "Update compose compiler metric and report"
          git status
          git push
