name: Build (Android)
on:
  push: 
    paths:
      - 'noty-android/**'
  pull_request:
    paths:
      - 'noty-android/**'

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Permission to Execute
        run: chmod +x gradlew
        working-directory: noty-android

      - name: ðŸ— Build with Gradle ðŸ› ï¸
        run: ./gradlew build --stacktrace
        working-directory: noty-android

      - name: ðŸš€ Upload APK ðŸ“±
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: noty-android/**/*.apk
          retention-days: 3

      - name: ðŸ“Š Generate compose compiler report ï¸
        if: github.event_name == 'push'
        run: |
          ./gradlew releaseComposeCompilerHtmlReport --stacktrace
          mv -f noty-android/app/composeapp/build/compose_report/index.html docs/pages/noty-android/compose_report.html
          git config user.name $GITHUB_ACTOR
          git config user.email action@github.com
          echo "Compose Report Generated by $GITHUB_RUN_NUMBER via $GITHUB_EVENT_NAME on $(date +"%Y-%m-%d %r")" > docs/pages/noty-android/compose_report.meta
          git add docs/pages/noty-android/compose_report.html
          git add docs/pages/noty-android/compose_report.meta
          git commit -m "Update compose compiler metric and report"
          git status
          git push
        working-directory: noty-android